FROM debian:11-slim
LABEL org.opencontainers.image.authors="<chasing66@live.com>"
WORKDIR /root
COPY entrypoint.sh /root/
RUN chmod +x entrypoint.sh
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates procps proxychains4 \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
COPY p2pclient /usr/bin/p2pclient
RUN chmod +x /usr/bin/p2pclient
ENTRYPOINT ["/root/entrypoint.sh"]